const other = [
  {
    id: 'circ',
    latex: '\\circ',
    offset: 0,
    shortcut: -1,
    order: 7,
  },
  {
    id: 'degree',
    latex: '^{\\circ}',
    offset: -8,
    shortcut: -1,
    order: 6,
  },
  {
    id: 'angle',
    latex: '\\angle{}',
    offset: -1,
    shortcut: -1,
    order: 5,
  },
  {
    id: 'triangle',
    latex: '\\triangle{}',
    offset: -1,
    shortcut: -1,
    order: 4,
  },
  {
    id: 'overline',
    latex: '\\overline{}',
    offset: -1,
    shortcut: -1,
    order: 0,
  },
  {
    id: 'overleftrightarrow',
    latex: '\\overleftrightarrow{}',
    offset: -1,
    shortcut: -1,
    order: 1,
  },
  {
    id: 'overrightarrow',
    latex: '\\overrightarrow{}',
    offset: -1,
    shortcut: -1,
    order: 2,
  },
  {
    id: 'arc',
    latex: '\\overset{\\frown}{}',
    offset: -1,
    shortcut: -1,
    order: 3,
  },
  {
    id: 'binom',
    latex: '\\binom{}{}',
    offset: -3,
    shortcut: -1,
    order: 8,
  },
  {
    id: 'simultaneous-equations',
    latex: '\\begin{cases} {} &{} \\\\ {} &{} \\end{cases}',
    offset: -27,
    shortcut: -1,
    order: 9,
  },
  {
    id: 'infty',
    latex: '\\infty',
    offset: 0,
    shortcut: -1,
    order: 10,
  },
];

export default other;
